<center><b>First task<b\><center\>

0.05*x1 + 0.07*x2 + 0*x3 = 2250
0.05*x1 + 0*x2 +0.06*x3 = 1400
x1 + x2 + x3 = 50000

In [1]:
import numpy as np

In [3]:
A = np.array([[0.05, 0.07, 0], [0.05, 0, 0.06], [1, 1, 1]])
b = np.array([2250, 1400, 50000]) 

In [4]:
A

array([[0.05, 0.07, 0.  ],
       [0.05, 0.  , 0.06],
       [1.  , 1.  , 1.  ]])

In [5]:
b

array([ 2250,  1400, 50000])

<center><b>1-st<b\><center\>

In [6]:
np.linalg.solve(A, b)

array([10000., 25000., 15000.])

<center><b>2-nd<b\><center\>

In [8]:
A_inv = np.linalg.inv(A)
A_inv

array([[ 26.08695652,  30.43478261,  -1.82608696],
       [ -4.34782609, -21.73913043,   1.30434783],
       [-21.73913043,  -8.69565217,   1.52173913]])

In [9]:
A_inv.dot(b)

array([10000., 25000., 15000.])

<center><b>3-rd<b\><center\>

In [11]:
a = np.linalg.det(A)
a

-0.002300000000000002

In [12]:
A1 = A.copy()
A1[:, 0] = b
A1

array([[2.25e+03, 7.00e-02, 0.00e+00],
       [1.40e+03, 0.00e+00, 6.00e-02],
       [5.00e+04, 1.00e+00, 1.00e+00]])

In [14]:
a1 = np.linalg.det(A1)
a1

-23.00000000000002

In [15]:
res1 = round(a1 / a,1)

10000.0

In [16]:
A2 = A.copy()
A2[:, 1] = b
a2 = np.linalg.det(A2)
res2 = round(a2 / a,1)
res2

25000.0

In [17]:
A3 = A.copy()
A3[:, 2] = b
a3 = np.linalg.det(A3)
res3 = round(a3 / a,1)
res3

15000.0

<center><b>Second Task<b\><center\>

x1 - x2 = -120
x1 - x3 = 100
x1 + x2 + x3 = 1328

In [18]:
A = np.array([[1, -1, 0], [1, 0, -1], [1, 1, 1]])
b = np.array([-120, 100, 1328]) 

In [20]:
np.linalg.solve(A, b)

array([436., 556., 336.])

<center><b>Third Task<b\><center\>

3/a^2 + 0/b^2 + 3/z^2 = 1
6/a^2 + 0.25/b^2 + 0/z^2 = 1
1/a^2 + 1/3^-2/b^2 + 1/z^2 = 1
Заміна:
1/a^2 = p, +-a = (1/p)^-2
1/b^2 = l, +-b = (1/l)^-2
1/z^2 = m, +-z = (1/m)^-2

In [34]:
A = np.array([[3, 0, 3], [6, 0.25, 0], [1, 1/3, 1]])
b = np.array([1, 1, 1])

In [44]:
p, l, m = np.linalg.solve(A, b)
res = np.array([])
res = np.append(res, [round(1/p,1),round(1/l,1),round(1/m,1)])
res

array([12. ,  0.5,  4. ])

<center><b>Fourth Task<b\><center\>

a + b + c = 12
9*a + 3*b + c = 54
a - b + c = 2

In [45]:
A = np.array([[1, 1, 1], [9, 3, 1], [1, -1, 1]])
b = np.array([12, 54, 2])

In [47]:
np.linalg.solve(A, b)

array([4., 5., 3.])

<center><b>Fifth Task<b\><center\>

In [76]:
from typing import List
def get_polynom(coords: List[tuple] = [(1,12), (3,54), (-1,2)]):
    matrix = []
    b = []
    n = len(coords)
    for x, y in coords:
        matrix.extend([x ** i for i in range(n)])
        b.append(y)
    matrix = np.array(matrix).reshape(n, n)
    b = np.array(b).reshape(n, 1)
    return np.linalg.solve(matrix, b)

In [77]:
get_polynom()

[1, 1, 1, 1, 3, 9, 1, -1, 1]
[12, 54, 2]


array([[3.],
       [5.],
       [4.]])