In [3]:
import numpy as np

In [4]:
l1 = np.array([1,2,3])

In [5]:
l1

array([1, 2, 3])

In [6]:
type(l1)

numpy.ndarray

In [7]:
l1.dtype

dtype('int64')

In [8]:
l2 = np.array([1, 'text', dict()])

In [9]:
l2.dtype

dtype('O')

In [10]:
l2

array([1, 'text', {}], dtype=object)

In [11]:
l3 = np.array([4,5,6],dtype='float')

In [12]:
l3

array([4., 5., 6.])

In [13]:
[1,2,3] + [4,5,6]

[1, 2, 3, 4, 5, 6]

In [14]:
l1+l3

array([5., 7., 9.])

In [15]:
l1-l3

array([-3., -3., -3.])

In [16]:
l1/l3

array([0.25, 0.4 , 0.5 ])

In [17]:
l1[0]

1

In [18]:
l1[-1]

3

In [19]:
matrix = np.array([[1 ,2 ,3],[4 ,5 ,6]])

In [20]:
matrix

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
matrix[0 ,1]

2

In [22]:
matrix2 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [23]:
matrix2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [24]:
matrix2[1:,:-1]

array([[ 5,  6,  7],
       [ 9, 10, 11]])

In [25]:
matrix3 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [26]:
matrix2 + matrix3

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

In [27]:
test = np.array([1,2,3,4])

In [28]:
test+matrix3

array([[ 2,  4,  6,  8],
       [ 6,  8, 10, 12],
       [10, 12, 14, 16]])

In [29]:
test = np.array([1,2,3])

In [30]:
test + matrix3

ValueError: operands could not be broadcast together with shapes (3,) (3,4) 

In [31]:
test = np.array([1, 2, 3, 4])

In [32]:
matrix = np.array([[1, 2, 3], [4, 5, 6]])
matrix

array([[1, 2, 3],
       [4, 5, 6]])

In [33]:
test.shape

(4,)

In [34]:
matrix.shape

(2, 3)

In [35]:
test.size

4

In [36]:
matrix.size

6

In [37]:
test.ndim

1

In [38]:
matrix.ndim

2

In [39]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [40]:
np.zeros((3, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [41]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [42]:
np.ones((5, 10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [43]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [44]:
np.arange(0, 1, 0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [45]:
np.linspace(0, 5, 10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [46]:
np.linspace(0, 5, 15)

array([0.        , 0.35714286, 0.71428571, 1.07142857, 1.42857143,
       1.78571429, 2.14285714, 2.5       , 2.85714286, 3.21428571,
       3.57142857, 3.92857143, 4.28571429, 4.64285714, 5.        ])

In [47]:
test

array([1, 2, 3, 4])

In [48]:
test.max()

4

In [49]:
test.min()

1

In [50]:
test.sum()

10

In [51]:
test.prod()

24

In [52]:
test.mean()

2.5

In [53]:
matrix.mean()

3.5

In [54]:
matrix.max()

6

In [55]:
matrix

array([[1, 2, 3],
       [4, 5, 6]])

In [56]:
matrix = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
matrix

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [57]:
matrix.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [58]:
matrix.reshape(2, 6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [59]:
matrix.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [60]:
m1 = np.array([[1, 2],[3, 4]])
m2 = np.array([[5, 6],[7, 8]])

In [61]:
m1

array([[1, 2],
       [3, 4]])

In [62]:
m2

array([[5, 6],
       [7, 8]])

In [63]:
m1 * m2

array([[ 5, 12],
       [21, 32]])

In [64]:
m1.dot(m2)

array([[19, 22],
       [43, 50]])

In [65]:
np.linalg.det(m1)

-2.0000000000000004

In [66]:
np.linalg.det(m2)

-2.000000000000005

In [67]:
np.linalg.inv(m1)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [68]:
np.linalg.eig(m1)

(array([-0.37228132,  5.37228132]),
 array([[-0.82456484, -0.41597356],
        [ 0.56576746, -0.90937671]]))

In [69]:
A = np.array([[5, 3, 2], [2, 4, 6], [2, 9 ,1]])
b = np.array([1, 8, 3])

In [70]:
A

array([[5, 3, 2],
       [2, 4, 6],
       [2, 9, 1]])

In [71]:
b

array([1, 8, 3])

In [72]:
A_inv = np.linalg.inv(A)

In [73]:
A_inv

array([[ 0.25 , -0.075, -0.05 ],
       [-0.05 , -0.005,  0.13 ],
       [-0.05 ,  0.195, -0.07 ]])

In [74]:
A_inv.dot(b)

array([-0.5,  0.3,  1.3])

In [75]:
a = np.linalg.det(A)
a

-199.99999999999991

In [76]:
A1 = A.copy()
A1[:,0] = b
A1

array([[1, 3, 2],
       [8, 4, 6],
       [3, 9, 1]])

In [77]:
a1 = np.linalg.det(A1)
a1

99.99999999999996

In [78]:
round(a1 / a, 1)

-0.5

In [79]:
A2 = A.copy()
A2[:,1] = b
A2

array([[5, 1, 2],
       [2, 8, 6],
       [2, 3, 1]])

In [80]:
a2 = np.linalg.det(A2)
a2

-60.000000000000036

In [81]:
round(a2 / a, 1)

0.3

In [82]:
A3 = A.copy()
A3[:,2] = b
A3

array([[5, 3, 1],
       [2, 4, 8],
       [2, 9, 3]])

In [83]:
a3 = np.linalg.det(A3)
a3

-259.99999999999994

In [84]:
round(a3 / a, 1)

1.3

In [85]:
np.linalg.solve(A, b)

array([-0.5,  0.3,  1.3])